### ISSUE TITLE
Obs type "quadratic" throws error if sampling period is too large for "bio2" benchmark

### ISSUE THREAD

**Issue by Abdu-Hekal** [EthanJamesLew/AutoKoopman#13]
For "larger" sampling periods in the "bio2" benchmark (sampling period >= 0.1), the returned "trajectory.states" from "model.solve_vp" returns rows with nan, such that the trajectory returned is incomplete. 
Whilst running it also throws: "RuntimeWarning: overflow encountered in double_scalars".

Could this be an inherit limitation of the obs type such that for more complex systems it requires a smaller sampling rate?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal could you put a code snippet in this issue that reproduces this error? Otherwise, could you email me what you have?

**Comment by EthanJamesLew** [comment]
Reducing the maximum rank seems to stabilize it. Given that the optimizer chooses the overflowed observables mapping, I will need to change the AutoKoopman hyperparameter optimizer to change this.

**Comment by EthanJamesLew** [comment]
We will not be using quadratic now that we have a decent polynomial. Closing for now
