### ISSUE TITLE
ODEs with Constraints

### ISSUE THREAD

**Issue by EthanJamesLew** [EthanJamesLew/AutoKoopman#19]
> I have been going through the benchmarks from the original Arch competition, and some of them have constraints that are not implemented. For example: “Prde20” has a constraint that: x(t) + y(t) + z(t) = 10 for all t.
Does Autokoopman currently have support for implementing these constraints for continuous systems? If not, could we add some support for constraints on dynamics?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal Our implementation of Prde20 should be valid if the initial conditions satisfy the equality $$x_0 + y_0 + z_0 = 10$$. This can be expressed as the DAE

$$
\begin{cases}
\dot x  = - \frac{x y}{x + 1} \\
\dot y  = \frac{x y}{x + 1} - \alpha y \\
10 = x + y + z \\ 
\end{cases}
$$ 

but it should be sufficient as is.

At any rate, I'm adding an implementation of DAEs, but this shouldn't be a blocker for the benchmarks.

**Comment by Abdu-Hekal** [comment]
@EthanJamesLew I believe for the prde20 benchmark, the condition must hold for all times t (shown in the image attached) and not only as an initial condition. 

If we can express the DAE as you outlined: 10 = x + y + z, then we can capture this condition correctly. 

<img width="1302" alt="prde20" src="https://user-images.githubusercontent.com/91421619/188031437-86dad871-815d-45af-8cc2-2c862f093088.png">

Thank you!

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal the evolution function should already enforce $$x(t) + y(t) + z(t) = c_0, \quad \forall t \in \mathbb R^+$$ where $$x_0 + y_0 + z_0 = c_0$$. The DAE complains about being overconstrained when having the 3 differential equations + 1 constraint. Can you find an initial condition where that's for the case?
