### ISSUE TITLE
Support for trigonometric functions 

### ISSUE THREAD

**Issue by Abdu-Hekal** [EthanJamesLew/AutoKoopman#21]
The spring benchmark has cosine and sine functions in its differential equations. Do SymbolicContinuousSystem currently support this? If not, could we add support for these functions?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal We have an example of trig functions and SymbolicContinuousSystem [here](https://github.com/EthanJamesLew/AutoKoopman/blob/bdb0ed3879603787b9bed9b1cc1c2fd7b5f519eb/autokoopman/benchmark/pendulum.py#L27).

**Comment by EthanJamesLew** [comment]
Closing for now. Feel free to re-open
