### ISSUE TITLE
Multiple progress bars for Deep Koopman

### ISSUE THREAD

**Issue by KochdumperNiklas** [EthanJamesLew/AutoKoopman#24]
For observable type "deep" multiple successive progress bars instead of a single progress bar are shown

![AutoKoopmanDeep](https://user-images.githubusercontent.com/94628247/196077813-97cd223f-c3a7-4842-b15a-62619946fc0e.png)

**Comment by EthanJamesLew** [comment]
@KochdumperNiklas should be fixed on main now
