### ISSUE TITLE
Unable to Run Benchmarks

### ISSUE THREAD

**Issue by EthanJamesLew** [EthanJamesLew/AutoKoopman#36]
**Summary**

I would like some help running the benchmarks on my side so I can troubleshoot issues. I am particularly confused by
```python
from glop import Glop
```
as I cannot find any library that has such an object (I think it's a linear program solver?)

@Abdu-Hekal may you please provide some instructions here?

**Comment by EthanJamesLew** [comment]
Of course, I figure it out right after filing an issue :) add `benchmarks` to PYTHONPATH. I still think a small writeup would be nice since that wasn't obvious to me.

**Comment by Abdu-Hekal** [comment]
Yes! sorry about that

**Comment by EthanJamesLew** [comment]
Closing
