### ISSUE TITLE
Assertion error for 1d inputs

### ISSUE THREAD

**Issue by Abdu-Hekal** [EthanJamesLew/AutoKoopman#74]
@EthanJamesLew For systems with 1 input, the following error is thrown: AssertionError: inputs must be able to be converted to 2D numpy array. How do we learn systems with only 1 input?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal the library should probably check for 1D inputs, but the logic should still be okay. You will need a nx1 2D array, and maybe use `np.atleast_2d` on the inputs to stop the error.
