### ISSUE TITLE
Suppress resampling trajectories message  

### ISSUE THREAD

**Issue by Abdu-Hekal** [EthanJamesLew/AutoKoopman#79]
@EthanJamesLew can we suppress the print message "resampling trajectories"? Or maybe have an option to disable.

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal that is a good feature and maybe justifies a more complete logging solution so we can turn off some messages and offer users (or ourselves) more customization in how to consume warning and logs. How soon do you need this by? I'm still out of office.

**Comment by Abdu-Hekal** [comment]
No rush at all! I agree, makes more sense to suppress it for falsification as AutoKoopman is called many times. A more complete logging solution with varying verbosity makes the most sense.
