### ISSUE TITLE
Weighting Trajectories for Evaluation

### ISSUE THREAD

**Issue by EthanJamesLew** [EthanJamesLew/AutoKoopman#84]
**Summary**
- [x] add weights for each trajectory for evaluation 

CC @Abdu-Hekal

**Comment by Abdu-Hekal** [comment]
Ideally for every N*M trajectory with N state variables and M time-steps, we could pass a N*M matrix of weights. So for a set of trajectories we have a set of these matrices. This would give use control over weights for each trajectory, state variable and time point

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal does [this code](https://github.com/EthanJamesLew/AutoKoopman/blob/a777adff6f98fe46b48aef2b589ca069e9892aa6/notebooks/weighted-cost-func.ipynb) work for you?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal ping

**Comment by Abdu-Hekal** [comment]
@EthanJamesLew code runs well, Thank you!

**Comment by Abdu-Hekal** [comment]
@EthanJamesLew Is it possible to have the weights defined for each state variable? so that different state variables can have different weights?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal I believe that is doable as it (pass in a T x N x M array instead of T x M array), but lemme check

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal I see the issue--try now?

**Comment by EthanJamesLew** [comment]
@Abdu-Hekal interesting. The GitHub CI/CD seemed to be okay with it: https://github.com/EthanJamesLew/AutoKoopman/actions/runs/8251423166/job/22568416799

**Comment by Abdu-Hekal** [comment]
@EthanJamesLew Interesting, when I run the notebook I first get this error:
AttributeError: 'UniformTimeTrajectory' object has no attribute 'abs'.
Then I replace  w = traj.abs().states with just w=abs(traj.states), and I run into the same error as before:
Error: operands could not be broadcast together with shapes (101,2) (101,)

**Comment by Abdu-Hekal** [comment]
@EthanJamesLew All good, Notebook Kernel just needed restarting :)
I am sometimes getting this warning though but does not seem detrimental
RuntimeWarning: overflow encountered in matmul
  return np.real(self._A @ obs.T).flatten()[: len(x)]

**Comment by EthanJamesLew** [comment]
Great! Closing for now
